LIBS=-ldl -lglfw -lGL
INC=-Ilibraries/GLM -Ilibraries/GLAD_V4.5/include -Ilibraries/GLFW_x32/inlcude

Rollercoaster: Main.cpp
	g++ libraries/GLAD_V4.5/src/glad.c Header.h ShaderBuilder.h Tools.h Tools.cpp ShaderBuilder.cpp Geometry.cpp Main.cpp -o Rollercoaster $(LIBS) $(INC)


